/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as unauthenticatedRouteRouteImport } from './routes/(unauthenticated)/route'
import { Route as commonRouteRouteImport } from './routes/(common)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as unauthenticatedRegisterRouteImport } from './routes/(unauthenticated)/register'
import { Route as unauthenticatedLoginRouteImport } from './routes/(unauthenticated)/login'
import { Route as commonUnauthorizedRouteImport } from './routes/(common)/unauthorized'
import { Route as commonNotFoundRouteImport } from './routes/(common)/not-found'
import { Route as commonErrorRouteImport } from './routes/(common)/error'
import { Route as authenticatedMeIndexRouteImport } from './routes/(authenticated)/me/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedMeSenhaIndexRouteImport } from './routes/(authenticated)/me/senha/index'
import { Route as authenticatedMeDadosIndexRouteImport } from './routes/(authenticated)/me/dados/index'
import { Route as authenticatedAdministracaoConfiguracoesIndexRouteImport } from './routes/(authenticated)/administracao/configuracoes/index'
import { Route as authenticatedAdministracaoSegurancaUsuariosOnlineIndexRouteImport } from './routes/(authenticated)/administracao/seguranca/usuarios-online/index'
import { Route as authenticatedAdministracaoSegurancaHistoricoLoginsIndexRouteImport } from './routes/(authenticated)/administracao/seguranca/historico-logins/index'
import { Route as authenticatedAdministracaoAcessoUsuariosIndexRouteImport } from './routes/(authenticated)/administracao/acesso/usuarios/index'
import { Route as authenticatedAdministracaoAcessoGruposIndexRouteImport } from './routes/(authenticated)/administracao/acesso/grupos/index'
import { Route as authenticatedAdministracaoAcessoUsuariosNovoIndexRouteImport } from './routes/(authenticated)/administracao/acesso/usuarios/novo/index'
import { Route as authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRouteImport } from './routes/(authenticated)/administracao/acesso/usuarios/$usuarioId/index'
import { Route as authenticatedAdministracaoAcessoGruposNovoIndexRouteImport } from './routes/(authenticated)/administracao/acesso/grupos/novo/index'
import { Route as authenticatedAdministracaoAcessoGruposGrupoIdIndexRouteImport } from './routes/(authenticated)/administracao/acesso/grupos/$grupoId/index'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const unauthenticatedRouteRoute = unauthenticatedRouteRouteImport.update({
  id: '/(unauthenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const commonRouteRoute = commonRouteRouteImport.update({
  id: '/(common)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const unauthenticatedRegisterRoute = unauthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const unauthenticatedLoginRoute = unauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const commonUnauthorizedRoute = commonUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => commonRouteRoute,
} as any)
const commonNotFoundRoute = commonNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => commonRouteRoute,
} as any)
const commonErrorRoute = commonErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => commonRouteRoute,
} as any)
const authenticatedMeIndexRoute = authenticatedMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedMeSenhaIndexRoute =
  authenticatedMeSenhaIndexRouteImport.update({
    id: '/me/senha/',
    path: '/me/senha/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedMeDadosIndexRoute =
  authenticatedMeDadosIndexRouteImport.update({
    id: '/me/dados/',
    path: '/me/dados/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdministracaoConfiguracoesIndexRoute =
  authenticatedAdministracaoConfiguracoesIndexRouteImport.update({
    id: '/administracao/configuracoes/',
    path: '/administracao/configuracoes/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdministracaoSegurancaUsuariosOnlineIndexRoute =
  authenticatedAdministracaoSegurancaUsuariosOnlineIndexRouteImport.update({
    id: '/administracao/seguranca/usuarios-online/',
    path: '/administracao/seguranca/usuarios-online/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdministracaoSegurancaHistoricoLoginsIndexRoute =
  authenticatedAdministracaoSegurancaHistoricoLoginsIndexRouteImport.update({
    id: '/administracao/seguranca/historico-logins/',
    path: '/administracao/seguranca/historico-logins/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdministracaoAcessoUsuariosIndexRoute =
  authenticatedAdministracaoAcessoUsuariosIndexRouteImport.update({
    id: '/administracao/acesso/usuarios/',
    path: '/administracao/acesso/usuarios/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdministracaoAcessoGruposIndexRoute =
  authenticatedAdministracaoAcessoGruposIndexRouteImport.update({
    id: '/administracao/acesso/grupos/',
    path: '/administracao/acesso/grupos/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdministracaoAcessoUsuariosNovoIndexRoute =
  authenticatedAdministracaoAcessoUsuariosNovoIndexRouteImport.update({
    id: '/administracao/acesso/usuarios/novo/',
    path: '/administracao/acesso/usuarios/novo/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRoute =
  authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRouteImport.update({
    id: '/administracao/acesso/usuarios/$usuarioId/',
    path: '/administracao/acesso/usuarios/$usuarioId/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdministracaoAcessoGruposNovoIndexRoute =
  authenticatedAdministracaoAcessoGruposNovoIndexRouteImport.update({
    id: '/administracao/acesso/grupos/novo/',
    path: '/administracao/acesso/grupos/novo/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdministracaoAcessoGruposGrupoIdIndexRoute =
  authenticatedAdministracaoAcessoGruposGrupoIdIndexRouteImport.update({
    id: '/administracao/acesso/grupos/$grupoId/',
    path: '/administracao/acesso/grupos/$grupoId/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/health': typeof HealthRoute
  '/error': typeof commonErrorRoute
  '/not-found': typeof commonNotFoundRoute
  '/unauthorized': typeof commonUnauthorizedRoute
  '/login': typeof unauthenticatedLoginRoute
  '/register': typeof unauthenticatedRegisterRoute
  '/': typeof authenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/me/': typeof authenticatedMeIndexRoute
  '/administracao/configuracoes/': typeof authenticatedAdministracaoConfiguracoesIndexRoute
  '/me/dados/': typeof authenticatedMeDadosIndexRoute
  '/me/senha/': typeof authenticatedMeSenhaIndexRoute
  '/administracao/acesso/grupos/': typeof authenticatedAdministracaoAcessoGruposIndexRoute
  '/administracao/acesso/usuarios/': typeof authenticatedAdministracaoAcessoUsuariosIndexRoute
  '/administracao/seguranca/historico-logins/': typeof authenticatedAdministracaoSegurancaHistoricoLoginsIndexRoute
  '/administracao/seguranca/usuarios-online/': typeof authenticatedAdministracaoSegurancaUsuariosOnlineIndexRoute
  '/administracao/acesso/grupos/$grupoId/': typeof authenticatedAdministracaoAcessoGruposGrupoIdIndexRoute
  '/administracao/acesso/grupos/novo/': typeof authenticatedAdministracaoAcessoGruposNovoIndexRoute
  '/administracao/acesso/usuarios/$usuarioId/': typeof authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRoute
  '/administracao/acesso/usuarios/novo/': typeof authenticatedAdministracaoAcessoUsuariosNovoIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/error': typeof commonErrorRoute
  '/not-found': typeof commonNotFoundRoute
  '/unauthorized': typeof commonUnauthorizedRoute
  '/login': typeof unauthenticatedLoginRoute
  '/register': typeof unauthenticatedRegisterRoute
  '/': typeof authenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/me': typeof authenticatedMeIndexRoute
  '/administracao/configuracoes': typeof authenticatedAdministracaoConfiguracoesIndexRoute
  '/me/dados': typeof authenticatedMeDadosIndexRoute
  '/me/senha': typeof authenticatedMeSenhaIndexRoute
  '/administracao/acesso/grupos': typeof authenticatedAdministracaoAcessoGruposIndexRoute
  '/administracao/acesso/usuarios': typeof authenticatedAdministracaoAcessoUsuariosIndexRoute
  '/administracao/seguranca/historico-logins': typeof authenticatedAdministracaoSegurancaHistoricoLoginsIndexRoute
  '/administracao/seguranca/usuarios-online': typeof authenticatedAdministracaoSegurancaUsuariosOnlineIndexRoute
  '/administracao/acesso/grupos/$grupoId': typeof authenticatedAdministracaoAcessoGruposGrupoIdIndexRoute
  '/administracao/acesso/grupos/novo': typeof authenticatedAdministracaoAcessoGruposNovoIndexRoute
  '/administracao/acesso/usuarios/$usuarioId': typeof authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRoute
  '/administracao/acesso/usuarios/novo': typeof authenticatedAdministracaoAcessoUsuariosNovoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(common)': typeof commonRouteRouteWithChildren
  '/(unauthenticated)': typeof unauthenticatedRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/(common)/error': typeof commonErrorRoute
  '/(common)/not-found': typeof commonNotFoundRoute
  '/(common)/unauthorized': typeof commonUnauthorizedRoute
  '/(unauthenticated)/login': typeof unauthenticatedLoginRoute
  '/(unauthenticated)/register': typeof unauthenticatedRegisterRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(authenticated)/me/': typeof authenticatedMeIndexRoute
  '/(authenticated)/administracao/configuracoes/': typeof authenticatedAdministracaoConfiguracoesIndexRoute
  '/(authenticated)/me/dados/': typeof authenticatedMeDadosIndexRoute
  '/(authenticated)/me/senha/': typeof authenticatedMeSenhaIndexRoute
  '/(authenticated)/administracao/acesso/grupos/': typeof authenticatedAdministracaoAcessoGruposIndexRoute
  '/(authenticated)/administracao/acesso/usuarios/': typeof authenticatedAdministracaoAcessoUsuariosIndexRoute
  '/(authenticated)/administracao/seguranca/historico-logins/': typeof authenticatedAdministracaoSegurancaHistoricoLoginsIndexRoute
  '/(authenticated)/administracao/seguranca/usuarios-online/': typeof authenticatedAdministracaoSegurancaUsuariosOnlineIndexRoute
  '/(authenticated)/administracao/acesso/grupos/$grupoId/': typeof authenticatedAdministracaoAcessoGruposGrupoIdIndexRoute
  '/(authenticated)/administracao/acesso/grupos/novo/': typeof authenticatedAdministracaoAcessoGruposNovoIndexRoute
  '/(authenticated)/administracao/acesso/usuarios/$usuarioId/': typeof authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRoute
  '/(authenticated)/administracao/acesso/usuarios/novo/': typeof authenticatedAdministracaoAcessoUsuariosNovoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/health'
    | '/error'
    | '/not-found'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/'
    | '/api/auth/$'
    | '/me/'
    | '/administracao/configuracoes/'
    | '/me/dados/'
    | '/me/senha/'
    | '/administracao/acesso/grupos/'
    | '/administracao/acesso/usuarios/'
    | '/administracao/seguranca/historico-logins/'
    | '/administracao/seguranca/usuarios-online/'
    | '/administracao/acesso/grupos/$grupoId/'
    | '/administracao/acesso/grupos/novo/'
    | '/administracao/acesso/usuarios/$usuarioId/'
    | '/administracao/acesso/usuarios/novo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/error'
    | '/not-found'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/'
    | '/api/auth/$'
    | '/me'
    | '/administracao/configuracoes'
    | '/me/dados'
    | '/me/senha'
    | '/administracao/acesso/grupos'
    | '/administracao/acesso/usuarios'
    | '/administracao/seguranca/historico-logins'
    | '/administracao/seguranca/usuarios-online'
    | '/administracao/acesso/grupos/$grupoId'
    | '/administracao/acesso/grupos/novo'
    | '/administracao/acesso/usuarios/$usuarioId'
    | '/administracao/acesso/usuarios/novo'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(common)'
    | '/(unauthenticated)'
    | '/health'
    | '/(common)/error'
    | '/(common)/not-found'
    | '/(common)/unauthorized'
    | '/(unauthenticated)/login'
    | '/(unauthenticated)/register'
    | '/(authenticated)/'
    | '/api/auth/$'
    | '/(authenticated)/me/'
    | '/(authenticated)/administracao/configuracoes/'
    | '/(authenticated)/me/dados/'
    | '/(authenticated)/me/senha/'
    | '/(authenticated)/administracao/acesso/grupos/'
    | '/(authenticated)/administracao/acesso/usuarios/'
    | '/(authenticated)/administracao/seguranca/historico-logins/'
    | '/(authenticated)/administracao/seguranca/usuarios-online/'
    | '/(authenticated)/administracao/acesso/grupos/$grupoId/'
    | '/(authenticated)/administracao/acesso/grupos/novo/'
    | '/(authenticated)/administracao/acesso/usuarios/$usuarioId/'
    | '/(authenticated)/administracao/acesso/usuarios/novo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  commonRouteRoute: typeof commonRouteRouteWithChildren
  unauthenticatedRouteRoute: typeof unauthenticatedRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unauthenticated)': {
      id: '/(unauthenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(common)': {
      id: '/(common)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof commonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(unauthenticated)/register': {
      id: '/(unauthenticated)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof unauthenticatedRegisterRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(unauthenticated)/login': {
      id: '/(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedLoginRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(common)/unauthorized': {
      id: '/(common)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof commonUnauthorizedRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(common)/not-found': {
      id: '/(common)/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof commonNotFoundRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(common)/error': {
      id: '/(common)/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof commonErrorRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(authenticated)/me/': {
      id: '/(authenticated)/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof authenticatedMeIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/me/senha/': {
      id: '/(authenticated)/me/senha/'
      path: '/me/senha'
      fullPath: '/me/senha/'
      preLoaderRoute: typeof authenticatedMeSenhaIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/me/dados/': {
      id: '/(authenticated)/me/dados/'
      path: '/me/dados'
      fullPath: '/me/dados/'
      preLoaderRoute: typeof authenticatedMeDadosIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/administracao/configuracoes/': {
      id: '/(authenticated)/administracao/configuracoes/'
      path: '/administracao/configuracoes'
      fullPath: '/administracao/configuracoes/'
      preLoaderRoute: typeof authenticatedAdministracaoConfiguracoesIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/administracao/seguranca/usuarios-online/': {
      id: '/(authenticated)/administracao/seguranca/usuarios-online/'
      path: '/administracao/seguranca/usuarios-online'
      fullPath: '/administracao/seguranca/usuarios-online/'
      preLoaderRoute: typeof authenticatedAdministracaoSegurancaUsuariosOnlineIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/administracao/seguranca/historico-logins/': {
      id: '/(authenticated)/administracao/seguranca/historico-logins/'
      path: '/administracao/seguranca/historico-logins'
      fullPath: '/administracao/seguranca/historico-logins/'
      preLoaderRoute: typeof authenticatedAdministracaoSegurancaHistoricoLoginsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/administracao/acesso/usuarios/': {
      id: '/(authenticated)/administracao/acesso/usuarios/'
      path: '/administracao/acesso/usuarios'
      fullPath: '/administracao/acesso/usuarios/'
      preLoaderRoute: typeof authenticatedAdministracaoAcessoUsuariosIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/administracao/acesso/grupos/': {
      id: '/(authenticated)/administracao/acesso/grupos/'
      path: '/administracao/acesso/grupos'
      fullPath: '/administracao/acesso/grupos/'
      preLoaderRoute: typeof authenticatedAdministracaoAcessoGruposIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/administracao/acesso/usuarios/novo/': {
      id: '/(authenticated)/administracao/acesso/usuarios/novo/'
      path: '/administracao/acesso/usuarios/novo'
      fullPath: '/administracao/acesso/usuarios/novo/'
      preLoaderRoute: typeof authenticatedAdministracaoAcessoUsuariosNovoIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/administracao/acesso/usuarios/$usuarioId/': {
      id: '/(authenticated)/administracao/acesso/usuarios/$usuarioId/'
      path: '/administracao/acesso/usuarios/$usuarioId'
      fullPath: '/administracao/acesso/usuarios/$usuarioId/'
      preLoaderRoute: typeof authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/administracao/acesso/grupos/novo/': {
      id: '/(authenticated)/administracao/acesso/grupos/novo/'
      path: '/administracao/acesso/grupos/novo'
      fullPath: '/administracao/acesso/grupos/novo/'
      preLoaderRoute: typeof authenticatedAdministracaoAcessoGruposNovoIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/administracao/acesso/grupos/$grupoId/': {
      id: '/(authenticated)/administracao/acesso/grupos/$grupoId/'
      path: '/administracao/acesso/grupos/$grupoId'
      fullPath: '/administracao/acesso/grupos/$grupoId/'
      preLoaderRoute: typeof authenticatedAdministracaoAcessoGruposGrupoIdIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedMeIndexRoute: typeof authenticatedMeIndexRoute
  authenticatedAdministracaoConfiguracoesIndexRoute: typeof authenticatedAdministracaoConfiguracoesIndexRoute
  authenticatedMeDadosIndexRoute: typeof authenticatedMeDadosIndexRoute
  authenticatedMeSenhaIndexRoute: typeof authenticatedMeSenhaIndexRoute
  authenticatedAdministracaoAcessoGruposIndexRoute: typeof authenticatedAdministracaoAcessoGruposIndexRoute
  authenticatedAdministracaoAcessoUsuariosIndexRoute: typeof authenticatedAdministracaoAcessoUsuariosIndexRoute
  authenticatedAdministracaoSegurancaHistoricoLoginsIndexRoute: typeof authenticatedAdministracaoSegurancaHistoricoLoginsIndexRoute
  authenticatedAdministracaoSegurancaUsuariosOnlineIndexRoute: typeof authenticatedAdministracaoSegurancaUsuariosOnlineIndexRoute
  authenticatedAdministracaoAcessoGruposGrupoIdIndexRoute: typeof authenticatedAdministracaoAcessoGruposGrupoIdIndexRoute
  authenticatedAdministracaoAcessoGruposNovoIndexRoute: typeof authenticatedAdministracaoAcessoGruposNovoIndexRoute
  authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRoute: typeof authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRoute
  authenticatedAdministracaoAcessoUsuariosNovoIndexRoute: typeof authenticatedAdministracaoAcessoUsuariosNovoIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedMeIndexRoute: authenticatedMeIndexRoute,
  authenticatedAdministracaoConfiguracoesIndexRoute:
    authenticatedAdministracaoConfiguracoesIndexRoute,
  authenticatedMeDadosIndexRoute: authenticatedMeDadosIndexRoute,
  authenticatedMeSenhaIndexRoute: authenticatedMeSenhaIndexRoute,
  authenticatedAdministracaoAcessoGruposIndexRoute:
    authenticatedAdministracaoAcessoGruposIndexRoute,
  authenticatedAdministracaoAcessoUsuariosIndexRoute:
    authenticatedAdministracaoAcessoUsuariosIndexRoute,
  authenticatedAdministracaoSegurancaHistoricoLoginsIndexRoute:
    authenticatedAdministracaoSegurancaHistoricoLoginsIndexRoute,
  authenticatedAdministracaoSegurancaUsuariosOnlineIndexRoute:
    authenticatedAdministracaoSegurancaUsuariosOnlineIndexRoute,
  authenticatedAdministracaoAcessoGruposGrupoIdIndexRoute:
    authenticatedAdministracaoAcessoGruposGrupoIdIndexRoute,
  authenticatedAdministracaoAcessoGruposNovoIndexRoute:
    authenticatedAdministracaoAcessoGruposNovoIndexRoute,
  authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRoute:
    authenticatedAdministracaoAcessoUsuariosUsuarioIdIndexRoute,
  authenticatedAdministracaoAcessoUsuariosNovoIndexRoute:
    authenticatedAdministracaoAcessoUsuariosNovoIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface commonRouteRouteChildren {
  commonErrorRoute: typeof commonErrorRoute
  commonNotFoundRoute: typeof commonNotFoundRoute
  commonUnauthorizedRoute: typeof commonUnauthorizedRoute
}

const commonRouteRouteChildren: commonRouteRouteChildren = {
  commonErrorRoute: commonErrorRoute,
  commonNotFoundRoute: commonNotFoundRoute,
  commonUnauthorizedRoute: commonUnauthorizedRoute,
}

const commonRouteRouteWithChildren = commonRouteRoute._addFileChildren(
  commonRouteRouteChildren,
)

interface unauthenticatedRouteRouteChildren {
  unauthenticatedLoginRoute: typeof unauthenticatedLoginRoute
  unauthenticatedRegisterRoute: typeof unauthenticatedRegisterRoute
}

const unauthenticatedRouteRouteChildren: unauthenticatedRouteRouteChildren = {
  unauthenticatedLoginRoute: unauthenticatedLoginRoute,
  unauthenticatedRegisterRoute: unauthenticatedRegisterRoute,
}

const unauthenticatedRouteRouteWithChildren =
  unauthenticatedRouteRoute._addFileChildren(unauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  commonRouteRoute: commonRouteRouteWithChildren,
  unauthenticatedRouteRoute: unauthenticatedRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
