INSERT INTO location.tb_estado (id, sigla, nome, status)
VALUES ('11', 'RO', 'RONDÔNIA', 'A'),
       ('12', 'AC', 'ACRE', 'A'),
       ('13', 'AM', 'AMAZONAS', 'A'),
       ('29', 'BA', 'BAHIA', 'A'),
       ('53', 'DF', 'DISTRITO FEDERAL', 'A'),
       ('52', 'GO', 'GOIÁS', 'A'),
       ('31', 'MG', 'MINAS GERAIS', 'A'),
       ('51', 'MT', 'MATO GROSSO', 'A'),
       ('25', 'PB', 'PARAÍBA', 'A'),
       ('22', 'PI', 'PIAUÍ', 'A'),
       ('33', 'RJ', 'RIO DE JANEIRO', 'A'),
       ('43', 'RS', 'RIO GRANDE DO SUL', 'A'),
       ('28', 'SE', 'SERGIPE', 'A'),
       ('17', 'TO', 'TOCANTINS', 'A'),
       ('27', 'AL', 'ALAGOAS', 'A'),
       ('16', 'AP', 'AMAPÁ', 'A'),
       ('23', 'CE', 'CEARÁ', 'A'),
       ('32', 'ES', 'ESPÍRITO SANTO', 'A'),
       ('21', 'MA', 'MARANHÃO', 'A'),
       ('50', 'MS', 'MATO GROSSO DO SUL', 'A'),
       ('15', 'PA', 'PARÁ', 'A'),
       ('26', 'PE', 'PERNAMBUCO', 'A'),
       ('41', 'PR', 'PARANÁ', 'A'),
       ('24', 'RN', 'RIO GRANDE DO NORTE', 'A'),
       ('14', 'RR', 'RORAIMA', 'A'),
       ('42', 'SC', 'SANTA CATARINA', 'A'),
       ('35', 'SP', 'SÃO PAULO', 'A');
