CREATE
EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;

CREATE SCHEMA IF NOT EXISTS plataformadmin;
CREATE SCHEMA IF NOT EXISTS notification;
CREATE SCHEMA IF NOT EXISTS location;

-- plataformadmin
GRANT
USAGE
ON
SCHEMA
plataformadmin TO
${app_role};
ALTER
DEFAULT PRIVILEGES IN SCHEMA plataformadmin
    GRANT
SELECT,
INSERT
,
UPDATE,
DELETE
ON TABLES TO
${app_role};
ALTER
DEFAULT PRIVILEGES IN SCHEMA plataformadmin
    GRANT USAGE,
SELECT
ON SEQUENCES TO ${app_role};
ALTER
DEFAULT PRIVILEGES IN SCHEMA plataformadmin
    GRANT EXECUTE ON FUNCTIONS TO
${app_role};

-- notification
GRANT
USAGE
ON
SCHEMA
notification TO
${app_role};
ALTER
DEFAULT PRIVILEGES IN SCHEMA notification
    GRANT
SELECT,
INSERT
,
UPDATE,
DELETE
ON TABLES TO
${app_role};
ALTER
DEFAULT PRIVILEGES IN SCHEMA notification
    GRANT USAGE,
SELECT
ON SEQUENCES TO ${app_role};
ALTER
DEFAULT PRIVILEGES IN SCHEMA notification
    GRANT EXECUTE ON FUNCTIONS TO
${app_role};

-- location
GRANT
USAGE
ON
SCHEMA
location TO
${app_role};
ALTER
DEFAULT PRIVILEGES IN SCHEMA location
    GRANT
SELECT,
INSERT
,
UPDATE,
DELETE
ON TABLES TO
${app_role};
ALTER
DEFAULT PRIVILEGES IN SCHEMA location
    GRANT USAGE,
SELECT
ON SEQUENCES TO ${app_role};
ALTER
DEFAULT PRIVILEGES IN SCHEMA location
    GRANT EXECUTE ON FUNCTIONS TO
${app_role};
