networks:
  starter-network:
    name: starter-network
    driver: bridge

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.150.1
    container_name: starter-otel-collector
    restart: unless-stopped
    env_file:
      - .env
    hostname: otel
    networks:
      starter-network:
        aliases:
          - otel
    volumes:
      - ./dependencias/opentelemetry/config-cloud.yaml:/etc/otelcol-contrib/config.yaml

  cadastros:
    image: starter-api-cadastros:${VERSION}
    container_name: starter-api-cadastros
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - OTEL_SERVICE_NAME=${CADASTROS_OTEL_SERVICE_NAME}
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=${ENVIRONMENT},service.namespace=${NAMESPACE},service.version=${VERSION}
    hostname: starter-api-cadastros
    networks:
      - starter-network
    ports:
      - '9000:8080'
    volumes:
      - ${FILE_PATH}:/servers/docker/app/files/
    depends_on:
      - otel-collector

  gestao:
    image: starter-webapp-gestao:${VERSION}
    container_name: starter-webapp-gestao
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - CADASTROS_URL=http://starter-api-cadastros:8080/api/v1
      - BETTER_AUTH_URL=${GESTAO_WEBAPP_URL}
    hostname: starter-webapp-gestao
    networks:
      - starter-network
    ports:
      - '5137:3000'
    depends_on:
      - cadastros
